// GENERATED by tool/gen_mock_stac_flow.py from tool/mock_flow_descriptors.json, using the backend's real Stac
// serializer. Edit the descriptors and regenerate; do not edit this file by hand.
import 'dart:convert';

final List<Map<String, dynamic>> kMockStacStages = (jsonDecode(r'''
[
 {
  "stageId": "fayda_verification",
  "title": "fayda_verification",
  "screenType": "GENERIC_FORM",
  "nativeHandler": null,
  "widget": {
   "type": "column",
   "children": [
    {
     "type": "kneth_text",
     "id": "fayda_number",
     "label": "fayda_number",
     "required": true,
     "order": 1,
     "dependsOn": [],
     "consentRequired": false,
     "regex": "^\\d{16}$"
    },
    {
     "type": "kneth_dropdown",
     "id": "region",
     "label": "region",
     "required": true,
     "order": 2,
     "dependsOn": [],
     "consentRequired": false,
     "options": [
      {
       "label": "Addis Ababa",
       "value": "addis_ababa"
      },
      {
       "label": "Oromia",
       "value": "oromia"
      },
      {
       "label": "Amhara",
       "value": "amhara"
      },
      {
       "label": "Tigray",
       "value": "tigray"
      },
      {
       "label": "Sidama",
       "value": "sidama"
      },
      {
       "label": "Somali",
       "value": "somali"
      }
     ]
    },
    {
     "type": "kneth_dropdown",
     "id": "district",
     "label": "district",
     "required": true,
     "order": 3,
     "dependsOn": [
      "region"
     ],
     "consentRequired": false,
     "dynamicConfig": {
      "endpoint": "/options/regions/{region}/districts",
      "method": "GET"
     }
    }
   ]
  }
 },
 {
  "stageId": "identification_card",
  "title": "identification_card",
  "screenType": "NATIVE_CAPTURE",
  "nativeHandler": "photo_capture",
  "widget": {
   "type": "kneth_photo_capture",
   "id": "identification_card",
   "label": "identification_card"
  }
 },
 {
  "stageId": "personal_info",
  "title": "personal_info",
  "screenType": "GENERIC_FORM",
  "nativeHandler": null,
  "widget": {
   "type": "column",
   "children": [
    {
     "type": "kneth_text",
     "id": "full_name",
     "label": "full_name",
     "required": true,
     "order": 1,
     "dependsOn": [],
     "consentRequired": false,
     "regex": "^[\\p{L}\\p{M}\\s/'.-]{1,64}$",
     "minLen": 3,
     "maxLen": 64
    },
    {
     "type": "kneth_text",
     "id": "mother_name",
     "label": "mother_name",
     "required": true,
     "order": 2,
     "dependsOn": [],
     "consentRequired": false,
     "regex": "^[\\p{L}\\p{M}\\s/'.-]{1,64}$",
     "minLen": 3,
     "maxLen": 64
    },
    {
     "type": "kneth_dropdown",
     "id": "language_preference",
     "label": "language_preference",
     "required": true,
     "order": 3,
     "dependsOn": [],
     "consentRequired": false,
     "options": [
      {
       "label": "Amharic",
       "value": "amharic"
      },
      {
       "label": "English",
       "value": "english"
      },
      {
       "label": "Afan Oromifa",
       "value": "afan_oromo"
      },
      {
       "label": "Tigrigna",
       "value": "tigrigna"
      }
     ]
    }
   ]
  }
 },
 {
  "stageId": "consent_signature",
  "title": "consent_signature",
  "screenType": "NATIVE_CAPTURE",
  "nativeHandler": "signature_capture",
  "widget": {
   "type": "kneth_signature_capture",
   "id": "consent_signature",
   "label": "consent_signature"
  }
 },
 {
  "stageId": "association_details",
  "title": "association_details",
  "screenType": "GENERIC_FORM",
  "nativeHandler": null,
  "widget": {
   "type": "column",
   "children": [
    {
     "type": "kneth_dropdown",
     "id": "association_type",
     "label": "association_type",
     "required": true,
     "order": 1,
     "dependsOn": [],
     "consentRequired": false,
     "options": [
      {
       "label": "Individual",
       "value": "Individual"
      },
      {
       "label": "Group",
       "value": "Group"
      }
     ]
    },
    {
     "type": "kneth_conditional",
     "property": {
      "isRequired": false,
      "isHidden": true,
      "dependsOn": [
       "association_type"
      ],
      "conditionalDependency": {
       "if": [
        {
         "field": "association_type",
         "op": "eq",
         "value": "Group"
        }
       ],
       "then": {
        "isRequired": true,
        "isHidden": false
       },
       "else": {
        "isRequired": false,
        "isHidden": true
       }
      }
     },
     "child": {
      "type": "kneth_text",
      "id": "company_name",
      "label": "company_name",
      "required": false,
      "order": 2,
      "dependsOn": [
       "association_type"
      ],
      "consentRequired": false
     }
    }
   ]
  }
 }
]
''') as List).cast<Map<String, dynamic>>();
