// The DEFAULT app (MockApiClient, as main.dart wires it) driving the real FlowScreen
// through the Stac path, now that Stac is the only renderer: the demo flow is served in
// Stac shape (generated by the backend's real serializer) and the flow state comes from
// the legacy route, exactly as against the real backend.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:sdui_demo/features/flow/data/flow_repository_impl.dart';
import 'package:sdui_demo/features/flow/domain/flow_manifest.dart';
import 'package:sdui_demo/features/flow/presentation/flow_notifier.dart';
import 'package:sdui_demo/features/flow/presentation/flow_screen.dart';
import 'package:sdui_demo/features/stac_rendering/presentation/stac_flow_stage_screen.dart';
import 'package:sdui_demo/services/api_client.dart';

import '../../support/stac_flow_harness.dart';
import 'stac_test_actions.dart';
import 'stac_test_harness.dart';

void main() {
  testWidgets('the demo flow runs on the default MockApiClient: cascade, photo stage, and an Amharic name accepted',
      (tester) async {
    SharedPreferences.setMockInitialValues({});
    final api = MockApiClient();
    await tester.pumpWidget(ProviderScope(
      overrides: [
        apiClientProvider.overrideWithValue(api),
        flowRepositoryProvider.overrideWithValue(FlowRepositoryImpl(apiClient: api)),
        stacMediaRepositoryProvider.overrideWithValue(FakeMediaStorageRepository()),
        stacPickPhotoProvider.overrideWithValue(() async => '/cache/id.jpg'),
      ],
      child: MaterialApp(home: FlowScreen(manifest: FlowManifest(workflowId: 'kyc_kyb_collection', clientId: 'demo-client'))),
    ));
    await tester.pumpAndSettle(const Duration(seconds: 1));

    // Stage 1: fayda_verification (regex-validated number, region -> district cascade, all from the Mock).
    expect(textFieldWith('fayda_number'), findsOneWidget);
    await tester.enterText(textFieldWith('fayda_number'), '1234567890123456');
    await choose(tester, 'Addis Ababa', dropdown: 0);
    await tester.pumpAndSettle(const Duration(seconds: 1));
    await choose(tester, 'Bole', dropdown: 1);
    await tapContinue(tester);
    await tester.pumpAndSettle(const Duration(seconds: 1));

    // Stage 2: the photo capture stage, rendered by the Stac parser.
    expect(find.text('Take photo'), findsOneWidget);
    await tester.tap(find.text('Take photo'));
    await tester.pumpAndSettle();
    await tapContinue(tester);
    await tester.pumpAndSettle(const Duration(seconds: 1));

    // Stage 3: personal_info. Amharic names pass the demo's Unicode-aware pattern
    // (the old ASCII-only pattern rejected them, STAC_MIGRATION_SCOPING.md section 14.1).
    expect(textFieldWith('full_name'), findsOneWidget);
    await tester.enterText(textFieldWith('full_name'), 'አበበ በቀለ');
    await tester.enterText(textFieldWith('mother_name'), 'ወይዘሮ ሰላም');
    await choose(tester, 'Amharic', dropdown: 0);
    await tapContinue(tester);
    await tester.pumpAndSettle(const Duration(seconds: 1));

    expect(find.textContaining('format is invalid'), findsNothing);
    expect(find.text('Sign inside the box below'), findsOneWidget, reason: 'advanced to the signature stage');

    final container = ProviderScope.containerOf(tester.element(find.byType(FlowScreen)));
    final state = container.read(flowNotifierProvider) as FlowViewReady;
    expect(state.caseState.allValues['personal_info.full_name'], 'አበበ በቀለ');
    expect(state.caseState.allValues['fayda_verification.district'], 'bole', reason: 'the value, not the label');
    expect(state.caseState.allValues['identification_card.filePath'], startsWith('/fake/captures/'));
  });
}
