import 'dart:math';

import 'package:flutter_test/flutter_test.dart';

import 'package:sdui_demo/services/api_client.dart';
import 'package:sdui_demo/services/app_exception.dart';

void main() {
  group('MockApiClient.injectedFailure (deterministic test-injection path)', () {
    test('throws the injected failure on the next call, for every method', () async {
      final client = MockApiClient();

      client.injectedFailure = const NetworkException();
      await expectLater(
        client.fetchFlowManifestStac(flowId: 'kyc_kyb_collection', clientId: 'c'),
        throwsA(isA<NetworkException>()),
      );

      client.injectedFailure = const AppTimeoutException();
      await expectLater(
        client.fetchOptions(
          clientId: 'client-1',
          workflowId: 'kyc_kyb_collection',
          fieldKey: 'district',
          dependencyValues: const {'region': 'Addis Ababa'},
        ),
        throwsA(isA<AppTimeoutException>()),
      );

      client.injectedFailure = const ServerException(500);
      await expectLater(
        client.submitCase(caseId: null, values: const {}),
        throwsA(isA<ServerException>()),
      );

      client.injectedFailure = const UnauthorizedException();
      await expectLater(
        client.uploadDocument(recordId: 'record-1', kind: 'identification_card', filePath: '/tmp/x.jpg'),
        throwsA(isA<UnauthorizedException>()),
      );
    });

    test('only fires once, then clears itself', () async {
      final client = MockApiClient()..injectedFailure = const NetworkException();

      await expectLater(
        client.fetchFlowManifestStac(flowId: 'kyc_kyb_collection', clientId: 'c'),
        throwsA(isA<NetworkException>()),
      );

      // Second call succeeds normally — the injected failure only applied
      // to the one call right after it was set.
      final manifest = await client.fetchFlowManifestStac(flowId: 'kyc_kyb_collection', clientId: 'c');
      expect(manifest.stages, isNotEmpty);
      expect(client.injectedFailure, isNull);
    });
  });

  test('enableDemoFailures is off by default, so the random demo-failure path never runs', () async {
    // Not a statistical check: enableDemoFailures gates the whole demo
    // path behind a plain `if`, so "off" means the random path is
    // unreachable, not merely unlikely — one call is enough to prove it.
    final client = MockApiClient();

    final manifest = await client.fetchFlowManifestStac(flowId: 'kyc_kyb_collection', clientId: 'c');

    expect(manifest.stages, isNotEmpty);
  });

  test('submitCase always returns a recordId, so demo/manual runs can exercise document upload', () async {
    final client = MockApiClient();

    final result = await client.submitCase(caseId: 'case-1', values: const {});

    expect(result.caseId, 'case-1');
    expect(result.recordId, isNotNull);
  });

  test('uploadDocument echoes the kind it was given', () async {
    final client = MockApiClient();

    final result = await client.uploadDocument(
      recordId: 'record-1',
      kind: 'identification_card',
      filePath: '/tmp/x.jpg',
    );

    expect(result.kind, 'identification_card');
  });

  test('enableDemoFailures, when explicitly enabled with a seeded Random, can simulate a failure', () async {
    // Seeded so this is deterministic despite exercising the "random" path
    // — this is testing that the demo mechanism *works*, not asserting
    // real randomness, which would be flaky by definition.
    // Seed 2's first nextDouble() is ~0.0008, comfortably inside the ~5%
    // demo-failure threshold — verified by hand, not guessed (a wrong seed
    // would just make this test pass for the wrong reason, waiting to time
    // out on `fetchFlowManifestStac`'s own delay instead of asserting anything).
    final client = MockApiClient(enableDemoFailures: true, demoRandom: Random(2));

    await expectLater(
      client.fetchFlowManifestStac(flowId: 'kyc_kyb_collection', clientId: 'c'),
      throwsA(isA<AppException>()),
    );
  });

  test('MockApiClient serves the demo flow in Stac shape (generated by the backend\'s real serializer)', () async {
    final manifest = await MockApiClient().fetchFlowManifestStac(flowId: 'kyc_kyb_collection', clientId: 'demo-client', caseId: 'c-1');

    expect(manifest.caseId, 'c-1', reason: 'a resumed case id is echoed back, as the real route does');
    expect(manifest.stages.map((s) => s['stageId']),
        ['fayda_verification', 'identification_card', 'personal_info', 'consent_signature', 'association_details']);
    final byId = {for (final s in manifest.stages) s['stageId'] as String: s};
    expect(byId['identification_card']!['widget'], containsPair('type', 'kneth_photo_capture'));
    expect(byId['consent_signature']!['widget'], containsPair('type', 'kneth_signature_capture'));
    final fayda = (byId['fayda_verification']!['widget'] as Map)['children'] as List;
    expect(fayda.map((c) => (c as Map)['type']), ['kneth_text', 'kneth_dropdown', 'kneth_dropdown']);
    // the demo's live dropdown, and the Unicode-aware name pattern
    expect((fayda.last as Map)['dynamicConfig'], isNotNull);
    final personal = ((byId['personal_info']!['widget'] as Map)['children'] as List).first as Map;
    expect(personal['regex'], r"^[\p{L}\p{M}\s/'.-]{1,64}$");
  });

  test('the Mock\'s district options are keyed by the region VALUE (what the Stac dropdown stores)', () async {
    final client = MockApiClient();
    final byValue = await client.fetchOptions(
        clientId: 'c', workflowId: 'w', fieldKey: 'district', dependencyValues: {'region': 'addis_ababa'});
    expect(byValue.map((o) => o.label), ['Bole', 'Yeka', 'Kirkos']);
    final byLabel = await client.fetchOptions(
        clientId: 'c', workflowId: 'w', fieldKey: 'district', dependencyValues: {'region': 'Addis Ababa'});
    expect(byLabel, isEmpty);
  });
}
