"""Generates lib/services/mock_stac_flow.dart: the Stac-shaped stages MockApiClient serves for its demo flow.

The demo flow is DEFINED in tool/mock_flow_descriptors.json (stage/field descriptors: this is the file to edit).
The Stac JSON is produced from it by the backend's REAL serializer (app.case.adapters.inbound.stac_manifest), so
the demo shows exactly what the real backend would emit and no second copy of the serializer's logic exists in
Dart. Regenerate after editing the descriptors:

  cd ../../backend/onboarding-platform && uv run python ../../apk_development/kneth/tool/gen_mock_stac_flow.py \
      ../../apk_development/kneth/tool/mock_flow_descriptors.json ../../apk_development/kneth/lib/services/mock_stac_flow.dart
"""
import json, sys
from app.case.domain.ports import ManifestField, ManifestStage
from app.case.adapters.inbound.stac_manifest import manifest_stage_to_stac

legacy = json.load(open(sys.argv[1]))
out = []
for s in legacy:
    fields = []
    for f in s.get("fields", []):
        p = f.get("property", {})
        fields.append(ManifestField(
            key=f["key"], field_type=f["type"], input_mode=f["inputMode"],
            is_required=p.get("isRequired", False), is_hidden=p.get("isHidden", False),
            depends_on=p.get("dependsOn", []), conditional_dependency=p.get("conditionalDependency"),
            options=p.get("options"), dynamic_config=p.get("dynamicConfig"),
            order=p.get("order", 0), regex=p.get("regex"), min_len=p.get("minLen"), max_len=p.get("maxLen"),
        ))
    out.append(manifest_stage_to_stac(ManifestStage(
        key=s["stageId"], scope="TENANT", screen_type=s["screenType"], skip_gap_check=False,
        fields=fields, native_handler=s.get("nativeHandler"))))

body = json.dumps(out, indent=1, ensure_ascii=False)
assert "'''" not in body
open(sys.argv[2], "w").write(f"""// GENERATED by tool/gen_mock_stac_flow.py from tool/mock_flow_descriptors.json, using the backend's real Stac
// serializer. Edit the descriptors and regenerate; do not edit this file by hand.
import 'dart:convert';

final List<Map<String, dynamic>> kMockStacStages = (jsonDecode(r'''
{body}
''') as List).cast<Map<String, dynamic>>();
""")
print("wrote", sys.argv[2], len(out), "stages")
